@startuml
title Расширение компилятора
|Компилятор|
start
:Синтаксический разбор;
:Начало фазы анализа;
 -[#darkred]-> Абстрактное синтаксическое дерево;
|#AntiqueWhite|Расширение|
:Извлечение метаданных;
 -[#darkred]-> Модель запроса;
:Верификация модели;
if (Верификация пройдена) then (нет)
    |Компилятор|
    :Вывод ошибок;
    stop
else (да)
    |Расширение|
    :Трансформация кода;
    -[#darkred]-> Трансформация файла;
endif
|Компилятор|
:Конец фазы анализа;
stop

@enduml


