@startuml

|Компилятор|
start
:Синтаксический разбор;
:Начало фазы анализа;
 -[#blue]-> Определение класса;
|#AntiqueWhite|Плагин|
:Извлечение метаданных;
:Генерация кода;
 -[#blue]-> Трансформация
файла;
|Компилятор|
:Конец фазы анализа;
stop

@enduml


