@startuml
title Расширение IDE
|IDEA|
start
:Индексация кода;
 -[#darkred]-> Узел синтаксического дерева;
|#AntiqueWhite|Расширение|
if (Инспекция обнаружила ошибку) then (да)
    :Уведомление об ошибке;
else (нет)
endif
|IDEA|
:Формирование результата анализа;
stop
@enduml