@startuml

|Gradle|
start
:Синхронизация проекта;
 -[#darkred]-> Проект;
|#AntiqueWhite|Расширение|
:Добавление зависимости на
библиотеку времени выполнения;
:Добавление расширения компилятора
 в проект;
:Добавление задачи на установку
расширения среды разработки;
 -[#darkred]->;
|Gradle|
:Конец синхронизации;
stop

@enduml