@startuml
title Функциональная модель системы
|IDE|
start
:Открытие проекта;
-[#darkred]-> Скрипт сборки;
|Gradle|
:Синхронизация;
-[#darkred]-> Проект;
partition Расширение_Gradle {
    fork
    #palegreen:Настройка компилятора;
    forkagain
    #palegreen:Настройка IDE;
    endfork
}
|IDE|
-[#darkred]-> Среда выполнения;
partition Расширение_IDE {
    #palegreen:Анализ кода;
}
-[#darkred]-> Результат анализа;
if (Есть ошибки) then (да)
    stop
else (нет)
    |Gradle|
    :Сборка проекта;
    -[#darkred]-> Компилируемые файлы;
    partition Расширение_Компилятора {
        |Compiler|
        #palegreen:Анализ кода;
        -[#darkred]-> Метаданные;
        #palegreen:Трансформация;
    }
    -[#darkred]-> Итоговый код;
    :Продолжение компиляции;
    stop
endif
@enduml
