@startuml
'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response

Программист -> IDE : Код
Программист <- IDE : Подсветка ошибок
Программист -> IDE : Выбор исправления
Программист <- IDE : Исправленный код

@enduml